// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    ActivityType,
} from "../Types";

export class ActivitiesLocationsTable extends Table<DBConnection, 'ActivitiesLocationsTable'> {
    locationId = this.autogeneratedPrimaryKey('location_id', 'int');
    locationType = this.column<ActivityType>('location_type', 'enum', 'ActivityType');
    locationName = this.column('location_name', 'string');
    locationCreated = this.column('location_created', 'localDateTime');
    locationUpdated = this.column('location_updated', 'localDateTime');
    locationDeleted = this.optionalColumnWithDefaultValue('location_deleted', 'localDateTime');

    constructor() {
        super('activities_locations');
    }
}


