// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    TemporalTypeAdapter,
} from "../TemporalTypeAdapter";
import {
    Mutation,
    MutationSeverity,
} from "../Types";
import {
    ZonedDateTime,
} from "../../Temporal";

export class ActivitiesLogsTable extends Table<DBConnection, 'ActivitiesLogsTable'> {
    mutationId = this.autogeneratedPrimaryKey('mutation_id', 'int');
    festivalId = this.column('festival_id', 'int');
    activityId = this.optionalColumnWithDefaultValue('activity_id', 'int');
    areaId = this.optionalColumnWithDefaultValue('area_id', 'int');
    timeslotId = this.optionalColumnWithDefaultValue('timeslot_id', 'int');
    locationId = this.optionalColumnWithDefaultValue('location_id', 'int');
    mutation = this.column<Mutation>('mutation', 'enum', 'Mutation');
    mutationFields = this.optionalColumnWithDefaultValue('mutation_fields', 'string');
    mutationSeverity = this.column<MutationSeverity>('mutation_severity', 'enum', 'MutationSeverity');
    mutationUserId = this.optionalColumnWithDefaultValue('mutation_user_id', 'int');
    mutationDate = this.column<ZonedDateTime>('mutation_date', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);

    constructor() {
        super('activities_logs');
    }
}

export const tActivitiesLogs = new ActivitiesLogsTable();

