// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    TemporalTypeAdapter,
} from "../TemporalTypeAdapter";
import {
    ZonedDateTime,
} from "../../Temporal";

export class ContentCategoryTable extends Table<DBConnection, 'ContentCategoryTable'> {
    categoryId = this.autogeneratedPrimaryKey('category_id', 'int');
    eventId = this.column('event_id', 'int');
    categoryTitle = this.column('category_title', 'string');
    categoryIcon = this.column('category_icon', 'string');
    categoryDescription = this.optionalColumnWithDefaultValue('category_description', 'string');
    categoryOrder = this.column('category_order', 'int');
    categoryCreated = this.column<ZonedDateTime>('category_created', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    categoryUpdated = this.column<ZonedDateTime>('category_updated', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    categoryDeleted = this.optionalColumnWithDefaultValue<ZonedDateTime>('category_deleted', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);

    constructor() {
        super('content_category');
    }
}


