// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    TemporalTypeAdapter,
} from "../TemporalTypeAdapter";
import {
    DisplayHelpRequestStatus,
} from "../Types";
import {
    ZonedDateTime,
} from "../../Temporal";

export class DisplaysTable extends Table<DBConnection, 'DisplaysTable'> {
    displayId = this.autogeneratedPrimaryKey('display_id', 'int');
    displayIdentifier = this.column('display_identifier', 'string');
    displayLabel = this.optionalColumnWithDefaultValue('display_label', 'string');
    displayEventId = this.optionalColumnWithDefaultValue('display_event_id', 'int');
    displayLocationId = this.optionalColumnWithDefaultValue('display_location_id', 'int');
    displayColor = this.optionalColumnWithDefaultValue('display_color', 'string');
    displayHelpRequestStatus = this.optionalColumnWithDefaultValue<DisplayHelpRequestStatus>('display_help_request_status', 'enum', 'DisplayHelpRequestStatus');
    displayCheckIn = this.column<ZonedDateTime>('display_check_in', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    displayCheckInIp = this.column('display_check_in_ip', 'string');
    displayLocked = this.column('display_locked', 'int');
    displayDeleted = this.optionalColumnWithDefaultValue<ZonedDateTime>('display_deleted', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);

    constructor() {
        super('displays');
    }
}


