// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    TemporalTypeAdapter,
} from "../TemporalTypeAdapter";
import {
    ZonedDateTime,
} from "../../Temporal";
import {
    DisplayHelpRequestTarget,
} from "../Types";

export class DisplaysRequestsTable extends Table<DBConnection, 'DisplaysRequestsTable'> {
    requestId = this.autogeneratedPrimaryKey('request_id', 'int');
    displayId = this.column('display_id', 'int');
    requestEventId = this.column('request_event_id', 'int');
    requestReceivedDate = this.column<ZonedDateTime>('request_received_date', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    requestReceivedTarget = this.column<DisplayHelpRequestTarget>('request_received_target', 'enum', 'DisplayHelpRequestTarget');
    requestAcknowledgedBy = this.optionalColumnWithDefaultValue('request_acknowledged_by', 'int');
    requestAcknowledgedDate = this.optionalColumnWithDefaultValue<ZonedDateTime>('request_acknowledged_date', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    requestClosedBy = this.optionalColumnWithDefaultValue('request_closed_by', 'int');
    requestClosedDate = this.optionalColumnWithDefaultValue<ZonedDateTime>('request_closed_date', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    requestClosedReason = this.optionalColumnWithDefaultValue('request_closed_reason', 'string');

    constructor() {
        super('displays_requests');
    }
}


