// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    TemporalTypeAdapter,
} from "../TemporalTypeAdapter";
import {
    EnvironmentPurpose,
} from "../Types";
import {
    ZonedDateTime,
} from "../../Temporal";

export class EnvironmentsTable extends Table<DBConnection, 'EnvironmentsTable'> {
    environmentId = this.autogeneratedPrimaryKey('environment_id', 'int');
    environmentColourDarkMode = this.column('environment_colour_dark_mode', 'string');
    environmentColourLightMode = this.column('environment_colour_light_mode', 'string');
    environmentDescription = this.column('environment_description', 'string');
    environmentDomain = this.column('environment_domain', 'string');
    environmentPurpose = this.columnWithDefaultValue<EnvironmentPurpose>('environment_purpose', 'enum', 'EnvironmentPurpose');
    environmentTitle = this.column('environment_title', 'string');
    environmentDeleted = this.optionalColumnWithDefaultValue<ZonedDateTime>('environment_deleted', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);

    constructor() {
        super('environments');
    }
}

export const tEnvironments = new EnvironmentsTable();

