// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    TemporalTypeAdapter,
} from "../TemporalTypeAdapter";
import {
    ZonedDateTime,
} from "../../Temporal";

export class ErrorLogsTable extends Table<DBConnection, 'ErrorLogsTable'> {
    errorId = this.autogeneratedPrimaryKey('error_id', 'int');
    errorDate = this.column<ZonedDateTime>('error_date', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    errorUserId = this.optionalColumnWithDefaultValue('error_user_id', 'int');
    errorIpAddress = this.optionalColumnWithDefaultValue('error_ip_address', 'string');
    errorOrigin = this.column('error_origin', 'string');
    errorPathname = this.column('error_pathname', 'string');
    errorName = this.column('error_name', 'string');
    errorMessage = this.column('error_message', 'string');
    errorStack = this.optionalColumnWithDefaultValue('error_stack', 'string');
    errorDigest = this.optionalColumnWithDefaultValue('error_digest', 'string');

    constructor() {
        super('error_logs');
    }
}


