// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    TemporalTypeAdapter,
} from "../TemporalTypeAdapter";
import {
    PlainDate,
    ZonedDateTime,
} from "../../Temporal";

export class EventsDeadlinesTable extends Table<DBConnection, 'EventsDeadlinesTable'> {
    deadlineId = this.autogeneratedPrimaryKey('deadline_id', 'int');
    eventId = this.column('event_id', 'int');
    deadlineDate = this.column<PlainDate>('deadline_date', 'customLocalDate', 'date', TemporalTypeAdapter);
    deadlineOwnerId = this.optionalColumnWithDefaultValue('deadline_owner_id', 'int');
    deadlineTitle = this.column('deadline_title', 'string');
    deadlineDescription = this.column('deadline_description', 'string');
    deadlineCompleted = this.optionalColumnWithDefaultValue<ZonedDateTime>('deadline_completed', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    deadlineDeleted = this.optionalColumnWithDefaultValue<ZonedDateTime>('deadline_deleted', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);

    constructor() {
        super('events_deadlines');
    }
}

export const tEventsDeadlines = new EventsDeadlinesTable();

