// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    TemporalTypeAdapter,
} from "../TemporalTypeAdapter";
import {
    ZonedDateTime,
} from "../../Temporal";

export class FeedbackTable extends Table<DBConnection, 'FeedbackTable'> {
    feedbackId = this.autogeneratedPrimaryKey('feedback_id', 'int');
    userId = this.optionalColumnWithDefaultValue('user_id', 'int');
    feedbackName = this.optionalColumnWithDefaultValue('feedback_name', 'string');
    feedbackDate = this.column<ZonedDateTime>('feedback_date', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    feedbackText = this.column('feedback_text', 'string');

    constructor() {
        super('feedback');
    }
}


