// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";

export class HotelsAssignmentsTable extends Table<DBConnection, 'HotelsAssignmentsTable'> {
    assignmentId = this.autogeneratedPrimaryKey('assignment_id', 'int');
    eventId = this.column('event_id', 'int');
    assignmentBooked = this.columnWithDefaultValue('assignment_booked', 'int');
    assignmentHotelId = this.column('assignment_hotel_id', 'int');
    assignmentCheckIn = this.column('assignment_check_in', 'localDate');
    assignmentCheckOut = this.column('assignment_check_out', 'localDate');
    assignmentP1UserId = this.optionalColumnWithDefaultValue('assignment_p1_user_id', 'int');
    assignmentP1Name = this.optionalColumnWithDefaultValue('assignment_p1_name', 'string');
    assignmentP2UserId = this.optionalColumnWithDefaultValue('assignment_p2_user_id', 'int');
    assignmentP2Name = this.optionalColumnWithDefaultValue('assignment_p2_name', 'string');
    assignmentP3UserId = this.optionalColumnWithDefaultValue('assignment_p3_user_id', 'int');
    assignmentP3Name = this.optionalColumnWithDefaultValue('assignment_p3_name', 'string');
    assignmentVisible = this.columnWithDefaultValue('assignment_visible', 'int');

    constructor() {
        super('hotels_assignments');
    }
}


