// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";

export class HotelsAssignmentsTable extends Table<DBConnection, 'HotelsAssignmentsTable'> {
    assignmentId = this.autogeneratedPrimaryKey('assignment_id', 'int');
    bookingId = this.column('booking_id', 'int');
    eventId = this.column('event_id', 'int');
    assignmentUserId = this.optionalColumnWithDefaultValue('assignment_user_id', 'int');
    assignmentName = this.optionalColumnWithDefaultValue('assignment_name', 'string');
    assignmentPrimary = this.columnWithDefaultValue('assignment_primary', 'int');
    assignmentCreated = this.columnWithDefaultValue('assignment_created', 'localDateTime');

    constructor() {
        super('hotels_assignments');
    }
}


