// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    DateTimeTypeAdapter,
} from "../DateTimeTypeAdapter";
import {
    DateTime,
} from "../../DateTime";

export class NardoTable extends Table<DBConnection, 'NardoTable'> {
    nardoId = this.autogeneratedPrimaryKey('nardo_id', 'int');
    nardoAdvice = this.column('nardo_advice', 'string');
    nardoAuthorId = this.column('nardo_author_id', 'int');
    nardoAuthorDate = this.columnWithDefaultValue<DateTime>('nardo_author_date', 'customComparable', 'timestamp', DateTimeTypeAdapter);
    nardoVisible = this.columnWithDefaultValue('nardo_visible', 'int');

    constructor() {
        super('nardo');
    }
}


