// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    TemporalTypeAdapter,
} from "../TemporalTypeAdapter";
import {
    ZonedDateTime,
} from "../../Temporal";

export class OutboxTwilioTable extends Table<DBConnection, 'OutboxTwilioTable'> {
    outboxTwilioId = this.autogeneratedPrimaryKey('outbox_twilio_id', 'int');
    outboxTimestamp = this.column<ZonedDateTime>('outbox_timestamp', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    outboxSender = this.column('outbox_sender', 'string');
    outboxSenderUserId = this.optionalColumnWithDefaultValue('outbox_sender_user_id', 'int');
    outboxRecipient = this.column('outbox_recipient', 'string');
    outboxRecipientUserId = this.column('outbox_recipient_user_id', 'int');
    outboxMessage = this.column('outbox_message', 'string');

    constructor() {
        super('outbox_twilio');
    }
}


