/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    RoleBadge,
} from "../Types";

export class RolesTable extends Table<DBConnection, 'RolesTable'> {
    roleId = this.autogeneratedPrimaryKey('role_id', 'int');
    roleName = this.column('role_name', 'string');
    roleBadge = this.optionalColumnWithDefaultValue<RoleBadge>('role_badge', 'enum', 'RoleBadge');
    roleOrder = this.columnWithDefaultValue('role_order', 'int');
    roleAdminAccess = this.columnWithDefaultValue('role_admin_access', 'int');
    roleHotelEligible = this.columnWithDefaultValue('role_hotel_eligible', 'int');

    constructor() {
        super('roles');
    }
}


