// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    TemporalTypeAdapter,
} from "../TemporalTypeAdapter";
import {
    ScheduleType,
} from "../Types";
import {
    ZonedDateTime,
} from "../../Temporal";

export class ScheduleTable extends Table<DBConnection, 'ScheduleTable'> {
    scheduleId = this.autogeneratedPrimaryKey('schedule_id', 'int');
    scheduleType = this.column<ScheduleType>('schedule_type', 'enum', 'ScheduleType');
    userId = this.column('user_id', 'int');
    eventId = this.column('event_id', 'int');
    shiftId = this.optionalColumnWithDefaultValue('shift_id', 'int');
    scheduleTimeStart = this.column<ZonedDateTime>('schedule_time_start', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    scheduleTimeEnd = this.column<ZonedDateTime>('schedule_time_end', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);

    constructor() {
        super('schedule');
    }
}


