/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    ServiceLogResult ,
} from "../Types";

export class ServicesLogsTable extends Table<DBConnection, 'ServicesLogsTable'> {
    serviceLogId = this.autogeneratedPrimaryKey('service_log_id', 'int');
    serviceId = this.column('service_id', 'int');
    serviceLogTimestamp = this.columnWithDefaultValue('service_log_timestamp', 'localDateTime');
    serviceLogResult = this.column<ServiceLogResult >('service_log_result', 'enum', 'ServiceLogResult ');
    serviceLogRuntime = this.column('service_log_runtime', 'double');
    serviceLogData = this.column('service_log_data', 'string');

    constructor() {
        super('services_logs');
    }
}


