// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    TemporalTypeAdapter,
} from "../TemporalTypeAdapter";
import {
    ZonedDateTime,
} from "../../Temporal";

export class ShiftsCategoriesTable extends Table<DBConnection, 'ShiftsCategoriesTable'> {
    shiftCategoryId = this.autogeneratedPrimaryKey('shift_category_id', 'int');
    shiftCategoryName = this.column('shift_category_name', 'string');
    shiftCategoryColour = this.column('shift_category_colour', 'string');
    shiftCategoryExcitement = this.column('shift_category_excitement', 'double');
    shiftCategoryOrder = this.column('shift_category_order', 'int');
    shiftCategoryDeleted = this.optionalColumnWithDefaultValue<ZonedDateTime>('shift_category_deleted', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);

    constructor() {
        super('shifts_categories');
    }
}


