/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    FileType,
} from "../Types";

export class StorageTable extends Table<DBConnection, 'StorageTable'> {
    fileId = this.autogeneratedPrimaryKey('file_id', 'int');
    fileHash = this.column('file_hash', 'string');
    fileType = this.column<FileType>('file_type', 'enum', 'FileType');
    fileDate = this.column('file_date', 'localDateTime');
    fileData = this.column<Uint8Array>('file_data', 'custom', 'Blob');
    userId = this.column('user_id', 'int');

    constructor() {
        super('storage');
    }
}


