// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    SubscriptionChannel,
    SubscriptionChannelApplications,
} from "../Types";

export class SubscriptionsTable extends Table<DBConnection, 'SubscriptionsTable'> {
    subscriptionId = this.autogeneratedPrimaryKey('subscription_id', 'int');
    subscriptionUserId = this.column('subscription_user_id', 'int');
    subscriptionChannel = this.column<SubscriptionChannel>('subscription_channel', 'enum', 'SubscriptionChannel');
    subscriptionChannelApplications = this.optionalColumnWithDefaultValue<SubscriptionChannelApplications>('subscription_channel_applications', 'enum', 'SubscriptionChannelApplications');

    constructor() {
        super('subscriptions');
    }
}


