// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    SubscriptionType,
} from "../Types";

export class SubscriptionsTable extends Table<DBConnection, 'SubscriptionsTable'> {
    subscriptionId = this.autogeneratedPrimaryKey('subscription_id', 'int');
    subscriptionUserId = this.column('subscription_user_id', 'int');
    subscriptionType = this.column<SubscriptionType>('subscription_type', 'enum', 'SubscriptionType');
    subscriptionTypeId = this.optionalColumnWithDefaultValue('subscription_type_id', 'int');
    subscriptionChannelEmail = this.column('subscription_channel_email', 'int');
    subscriptionChannelNotification = this.column('subscription_channel_notification', 'int');
    subscriptionChannelSms = this.column('subscription_channel_sms', 'int');
    subscriptionChannelWhatsapp = this.column('subscription_channel_whatsapp', 'int');

    constructor() {
        super('subscriptions');
    }
}


