// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    TaskResult,
} from "../Types";

export class TasksTable extends Table<DBConnection, 'TasksTable'> {
    taskId = this.autogeneratedPrimaryKey('task_id', 'int');
    taskName = this.column('task_name', 'string');
    taskParams = this.column('task_params', 'string');
    taskParentTaskId = this.optionalColumnWithDefaultValue('task_parent_task_id', 'int');
    taskScheduledDate = this.columnWithDefaultValue('task_scheduled_date', 'localDateTime');
    taskScheduledIntervalMs = this.optionalColumnWithDefaultValue('task_scheduled_interval_ms', 'int');
    taskInvocationResult = this.optionalColumnWithDefaultValue<TaskResult>('task_invocation_result', 'enum', 'TaskResult');
    taskInvocationLogs = this.optionalColumnWithDefaultValue('task_invocation_logs', 'string');
    taskInvocationTimeMs = this.optionalColumnWithDefaultValue('task_invocation_time_ms', 'double');

    constructor() {
        super('tasks');
    }
}


