// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";

export class TeamsTable extends Table<DBConnection, 'TeamsTable'> {
    teamId = this.autogeneratedPrimaryKey('team_id', 'int');
    teamName = this.column('team_name', 'string');
    teamTitle = this.column('team_title', 'string');
    teamDescription = this.column('team_description', 'string');
    teamEnvironment = this.column('team_environment', 'string');
    teamColourDarkTheme = this.column('team_colour_dark_theme', 'string');
    teamColourLightTheme = this.column('team_colour_light_theme', 'string');

    constructor() {
        super('teams');
    }
}


