// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    DateTimeTypeAdapter,
} from "../DateTimeTypeAdapter";
import {
    DateTime,
} from "../../DateTime";

export class TrainingsExtraTable extends Table<DBConnection, 'TrainingsExtraTable'> {
    trainingExtraId = this.autogeneratedPrimaryKey('training_extra_id', 'int');
    eventId = this.column('event_id', 'int');
    trainingExtraName = this.columnWithDefaultValue('training_extra_name', 'string');
    trainingExtraEmail = this.columnWithDefaultValue('training_extra_email', 'string');
    trainingExtraBirthdate = this.optionalColumnWithDefaultValue<DateTime>('training_extra_birthdate', 'customComparable', 'date', DateTimeTypeAdapter);
    trainingExtraVisible = this.columnWithDefaultValue('training_extra_visible', 'int');

    constructor() {
        super('trainings_extra');
    }
}


