// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    DateTimeTypeAdapter,
} from "../DateTimeTypeAdapter";
import {
    DateTime,
} from "../../DateTime";

export class UsersPasskeysTable extends Table<DBConnection, 'UsersPasskeysTable'> {
    userPasskeyId = this.autogeneratedPrimaryKey('user_passkey_id', 'int');
    userId = this.column('user_id', 'int');
    credentialId = this.column<Buffer>('credential_id', 'custom', 'Blob');
    credentialName = this.optionalColumnWithDefaultValue('credential_name', 'string');
    credentialCreated = this.columnWithDefaultValue<DateTime>('credential_created', 'customComparable', 'dateTime', DateTimeTypeAdapter);
    credentialOrigin = this.column('credential_origin', 'string');
    credentialPublicKey = this.column<Buffer>('credential_public_key', 'custom', 'Blob');
    credentialDeviceType = this.column('credential_device_type', 'string');
    credentialBackedUp = this.column('credential_backed_up', 'int');
    credentialLastUsed = this.optionalColumnWithDefaultValue<DateTime>('credential_last_used', 'customComparable', 'dateTime', DateTimeTypeAdapter);
    counter = this.column('counter', 'bigint');

    constructor() {
        super('users_passkeys');
    }
}


