// @ts-nocheck
/* eslint-disable quotes, max-len */
/**
 * DO NOT EDIT:
 *
 * This file has been auto-generated from database schema using ts-sql-codegen.
 * Any changes will be overwritten.
 */
import { Table } from "ts-sql-query/Table";
import type { DBConnection } from "../Connection";
import {
    TemporalTypeAdapter,
} from "../TemporalTypeAdapter";
import {
    ZonedDateTime,
} from "../../Temporal";

export class VendorsScheduleTable extends Table<DBConnection, 'VendorsScheduleTable'> {
    vendorsScheduleId = this.autogeneratedPrimaryKey('vendors_schedule_id', 'int');
    vendorId = this.column('vendor_id', 'int');
    vendorsScheduleStart = this.column<ZonedDateTime>('vendors_schedule_start', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    vendorsScheduleEnd = this.column<ZonedDateTime>('vendors_schedule_end', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    vendorsScheduleCreated = this.column<ZonedDateTime>('vendors_schedule_created', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    vendorsScheduleUpdated = this.column<ZonedDateTime>('vendors_schedule_updated', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);
    vendorsScheduleDeleted = this.optionalColumnWithDefaultValue<ZonedDateTime>('vendors_schedule_deleted', 'customLocalDateTime', 'dateTime', TemporalTypeAdapter);

    constructor() {
        super('vendors_schedule');
    }
}

export const tVendorsSchedule = new VendorsScheduleTable();

