// Copyright 2023 Peter Beverloo & AnimeCon. All rights reserved.
// Use of this source code is governed by a MIT license that can be found in the LICENSE file.

import { NardoDataTable } from './NardoDataTable';
import { NardoPersonalisedDataTable } from './NardoPersonalisedDataTable';
import { Section } from '../../components/Section';
import { SectionIntroduction } from '../../components/SectionIntroduction';
import { createGenerateMetadataFn } from '../../lib/generatePageMetadata';
import { requireAuthenticationContext } from '@lib/auth/AuthenticationContext';

/**
 * This is the main landing page for the Del a Rie Advies service. It allows the volunteer to manage
 * the advice made available by our wonderful friends of Del a Rie Advies.
 */
export default async function DelARieAdviesPage() {
    await requireAuthenticationContext({
        check: 'admin',
        permission: 'organisation.nardo',
    });

    return (
        <>
            <Section title="Del a Rie Advies">
                <SectionIntroduction>
                    This is the exclusive repertoire demonstrating the best of what <strong>Del a
                    Rie Advies</strong> has to offer. As all advice will be published immediately,
                    please be concious of the diverse nature of our audience and keep it somewhat
                    reasonable.
                </SectionIntroduction>
                <NardoDataTable />
            </Section>
            <Section title="Personalised Del a Rie Advies">
                <SectionIntroduction>
                    These are pieces of personalised advice generated by Del a Rie Advies. They are
                    listed for inspection only: generation happens through the schedule.
                </SectionIntroduction>
                <NardoPersonalisedDataTable />
            </Section>
        </>
    );
}

export const generateMetadata = createGenerateMetadataFn('Del a Rie Advies', 'Organisation');
