// Copyright 2023 Peter Beverloo & AnimeCon. All rights reserved.
// Use of this source code is governed by a MIT license that can be found in the LICENSE file.

import { notFound } from 'next/navigation';
import { z } from 'zod';

import type { ActionProps } from '../Action';
import { ApproveVolunteerPromptBuilder } from './prompts/ApproveVolunteerPromptBuilder';
import { PromptBuilder } from './prompts/PromptBuilder';
import { RejectVolunteerPromptBuilder } from './prompts/RejectVolunteerPromptBuilder';
import { executeAccessCheck } from '@lib/auth/AuthenticationContext';

/**
 * Interface definition for the Generative AI API, exposed through /api/ai.
 */
export const kGeneratePromptDefinition = z.object({
    request: z.object({
        /**
         * Type of prompt that is being generated. Conveyed in the URL.
         */
        type: z.enum([
            'approve-volunteer',
            'cancel-participation',
            'change-team',
            'reinstate-participation',
            'reject-volunteer',
        ]),

        /**
         * In which language should the prompt be written?
         */
        language: z.enum([ 'Dutch', 'English' ]),

        /**
         * Parameters that can be passed when the `type` equals `approve-volunteer`.
         */
        approveVolunteer: z.object({
            event: z.string(),
        }).optional(),

        // TODO: cancel-participation
        // TODO: change-team
        // TODO: reinstate-participation

        /**
         * Parameters that can be passed when the `type` equals `reject-volunteer`.
         */
        rejectVolunteer: z.object({
            event: z.string(),
        }).optional(),

    }),
    response: z.strictObject({
        /**
         * Whether the prompt could be generated successfully.
         */
        success: z.boolean(),

        // -----------------------------------------------------------------------------------------
        // Success case:
        // -----------------------------------------------------------------------------------------

        /**
         * In case of success, the context that was considered in this generated prompt.
         */
        context: z.array(z.string()).optional(),

        /**
         * In case of success, the prompt that was used to generate the message.
         */
        prompt: z.string().optional(),

        /**
         * Result of the generated prompt. Split between an optional subject and a message.
         */
        result: z.strictObject({
            /**
             * The subject that should be associated with the generated message.
             */
            subject: z.string().optional(),

            /**
             * The message that was generated by this prompt.
             */
            message: z.string(),

        }).optional(),

        // -----------------------------------------------------------------------------------------
        // Failure case:
        // -----------------------------------------------------------------------------------------

        /**
         * In case of error, a textual description of what went wrong.
         */
        error: z.string().optional(),
    }),
});

export type GeneratePromptDefinition = z.infer<typeof kGeneratePromptDefinition>;

type Request = GeneratePromptDefinition['request'];
type Response = GeneratePromptDefinition['response'];

/**
 * API that allows AI-related settings to be updated.
 */
export async function generatePrompt(request: Request, props: ActionProps): Promise<Response> {
    // TODO: Permission checks.

    if (!props.user)
        notFound();

    const userId = props.user.userId;

    let generator: PromptBuilder<any, any>;
    switch (request.type) {
        case 'approve-volunteer':
            generator = new ApproveVolunteerPromptBuilder(userId, request.approveVolunteer);
            break;

            // TODO: cancel-participation
            // TODO: change-team
            // TODO: reinstate-participation

        case 'reject-volunteer':
            generator = new RejectVolunteerPromptBuilder(userId, request.rejectVolunteer);
            break;

        default:
            return { success: false, error: 'This type of prompt is not yet supported.' };
    }

    const { context, prompt } = await generator.build(request.language);

    // TODO: Actually query Vertex AI
    const subject = generator.subject;
    const message = 'TODO';

    return { success: true, context, prompt, result: { subject, message } };
}
